In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from tensorflow.keras import utils
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import warnings

warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("iris.data", header=None, names=['sepal_length','sepal_width','petal_length','petal_width','species'])
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

# NN/MLP

In [3]:
X = df.values[:,:-1].astype(float)
Y = pd.get_dummies(df, columns=["species"], dtype="float").iloc[:,-3:].values
X.shape, Y.shape

((150, 4), (150, 3))

In [4]:
X[0],Y[0]

(array([5.1, 3.5, 1.4, 0.2]), array([1., 0., 0.]))

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120, 3), (30, 3))

In [6]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
# Compile model
model.compile(
    loss='categorical_crossentropy',
    optimizer=Adam(learning_rate=0.01),
    metrics=['accuracy'])

model.fit(X, Y, epochs=50, batch_size=10)

Epoch 1/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3140 - loss: 1.3755  
Epoch 2/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - accuracy: 0.7009 - loss: 0.9271
Epoch 3/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - accuracy: 0.7019 - loss: 0.7544
Epoch 4/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - accuracy: 0.7498 - loss: 0.6073
Epoch 5/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - accuracy: 0.9018 - loss: 0.5233
Epoch 6/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - accuracy: 0.9507 - loss: 0.4259
Epoch 7/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.8655 - loss: 0.3604
Epoch 8/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - accuracy: 0.9385 - loss: 0.3442
Epoch 9/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - accuracy: 0.9128 - loss: 0.3067
Epoch 10/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - accuracy: 0.9300 - loss: 0.2928
Epoch 11/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.9383 - loss: 0.2523
Epoch 12/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step

In [8]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"accuracy: {accuracy}")
print(f"loss: {loss}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.0546
accuracy: 1.0
loss: 0.054554399102926254


In [9]:
y_preds = np.argmax(model.predict(X_test), 1)
y_true = np.argmax(y_test, 1)
print("predicted label: ", y_preds)
print("ground-truth: ", y_true)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
predicted label:  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
ground-truth:  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [10]:
np.unique(y_true)

array([0, 1, 2], dtype=int64)

In [11]:
print(classification_report(y_true, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# SVM

In [12]:
y_train_2 = np.argmax(y_train, 1)
svmClf = SVC(kernel='linear')
svmClf.fit(X_train, y_train_2)
y_preds = svmClf.predict(X_test)
print(classification_report(y_true, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Decision Tree

In [13]:
dtreeClf = DecisionTreeClassifier(criterion="gini")
dtreeClf.fit(X_train, y_train_2)
y_preds = dtreeClf.predict(X_test)
print(classification_report(y_true, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# XGBoost

In [14]:
from xgboost import XGBClassifier

xgbClf = XGBClassifier()
xgbClf.fit(X_train, y_train_2)
y_preds = xgbClf.predict(X_test)
print(classification_report(y_true, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [15]:
from sklearn.ensemble import RandomForestClassifier

rfClf = RandomForestClassifier(n_estimators=50)
rfClf.fit(X_train, y_train_2)
y_preds = rfClf.predict(X_test)
print(classification_report(y_true, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [16]:
!pip list

Package                                  Version
---------------------------------------- --------------
absl-py                                  2.1.0
aiohttp                                  3.9.3
aiosignal                                1.3.1
altair                                   5.3.0
aniso8601                                9.0.1
annotated-types                          0.6.0
anyio                                    4.3.0
argon2-cffi                              23.1.0
argon2-cffi-bindings                     21.2.0
arrow                                    1.3.0
asgiref                                  3.8.1
asttokens                                2.4.1
astunparse                               1.6.3
async-lru                                2.0.4
attrs                                    23.2.0
azure-cognitiveservices-speech           1.29.0
azure-core                               1.30.0
azure-identity                           1.15.0
Babel                                    2.


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
!pip install watermark


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
%load_ext watermark
%watermark -v -m -p numpy,pandas,tensorflow,keras,sklearn,folium

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Python implementation: CPython
Python version       : 3.12.1
IPython version      : 8.22.2

numpy     : 1.26.4
pandas    : 2.1.3
tensorflow: 2.16.2
keras     : 3.4.1
sklearn   : 1.4.1.post1
folium    : 0.17.0

Compiler    : MSC v.1937 64 bit (AMD64)
OS          : Windows
Release     : 11
Machine     : AMD64
Processor   : AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
CPU cores   : 16
Architecture: 64bit



In [19]:
import pickle

In [20]:
# Save the model to a file
with open('iris_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [21]:
# Load the model from the file
with open('iris_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Now you can use the loaded model for predictions
predictions = loaded_model.predict(X_test)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[5.2611623e-04 9.5072305e-01 4.8750762e-02]
 [9.9953401e-01 4.6596333e-04 1.6781101e-13]
 [1.1757027e-08 9.7876391e-04 9.9902117e-01]
 [4.5165533e-04 8.9879465e-01 1.0075371e-01]
 [2.1142574e-04 9.6850866e-01 3.1279929e-02]
 [9.9917090e-01 8.2912127e-04 1.5514438e-12]
 [3.1380013e-03 9.9549317e-01 1.3687527e-03]
 [6.3369230e-06 8.0590159e-02 9.1940349e-01]
 [1.6743780e-04 6.0194725e-01 3.9788532e-01]
 [1.0373637e-03 9.9621922e-01 2.7434146e-03]
 [3.0984898e-05 1.8267597e-01 8.1729299e-01]
 [9.9902928e-01 9.7067904e-04 3.0983451e-12]
 [9.9986935e-01 1.3063980e-04 2.4034174e-14]
 [9.9890172e-01 1.0982424e-03 3.0136002e-12]
 [9.9956316e-01 4.3679753e-04 2.8994163e-13]
 [3.7077744e-04 9.4439763e-01 5.5231579e-02]
 [3.4021230e-07 3.8395594e-03 9.9616003e-01]
 [1.1380158e-03 9.9352187e-01 5.3401534e-03]
 [7.0364843e-04 8.9318264e-01 1.0611372e-01]
 [3.7517813e-07 3.9950307e-03 9.9600464e-01]
 [9.9742150e-01 2.5785586e-03 2.0349110e-11]
 [7.1573304e-05 2

In [22]:
import joblib
# Save the Model using joblib.dump()
joblib.dump(model, 'iris_model.joblib')

# Load the Model using joblib.load() 
loaded_model = joblib.load('iris_model.joblib')

# Make Predictions with the Loaded Model
predictions = loaded_model.predict(X_test)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[5.2611623e-04 9.5072305e-01 4.8750762e-02]
 [9.9953401e-01 4.6596333e-04 1.6781101e-13]
 [1.1757027e-08 9.7876391e-04 9.9902117e-01]
 [4.5165533e-04 8.9879465e-01 1.0075371e-01]
 [2.1142574e-04 9.6850866e-01 3.1279929e-02]
 [9.9917090e-01 8.2912127e-04 1.5514438e-12]
 [3.1380013e-03 9.9549317e-01 1.3687527e-03]
 [6.3369230e-06 8.0590159e-02 9.1940349e-01]
 [1.6743780e-04 6.0194725e-01 3.9788532e-01]
 [1.0373637e-03 9.9621922e-01 2.7434146e-03]
 [3.0984898e-05 1.8267597e-01 8.1729299e-01]
 [9.9902928e-01 9.7067904e-04 3.0983451e-12]
 [9.9986935e-01 1.3063980e-04 2.4034174e-14]
 [9.9890172e-01 1.0982424e-03 3.0136002e-12]
 [9.9956316e-01 4.3679753e-04 2.8994163e-13]
 [3.7077744e-04 9.4439763e-01 5.5231579e-02]
 [3.4021230e-07 3.8395594e-03 9.9616003e-01]
 [1.1380158e-03 9.9352187e-01 5.3401534e-03]
 [7.0364843e-04 8.9318264e-01 1.0611372e-01]
 [3.7517813e-07 3.9950307e-03 9.9600464e-01]
 [9.9742150e-01 2.5785586e-03 2.0349110e-11]
 [7.1573304e-05 2

In [23]:
# Save the model to a file
with open('iris_model.pkl', 'wb') as file:
    pickle.dump(model, file)
# Save the model to a file
with open('iris_svm.pkl', 'wb') as file:
    pickle.dump(svmClf, file)
# Save the model to a file
with open('iris_tr.pkl', 'wb') as file:
    pickle.dump(dtreeClf, file)
    # Save the model to a file
with open('iris_rf.pkl', 'wb') as file:
    pickle.dump(rfClf, file)
    # Save the model to a file
with open('iris_xgb.pkl', 'wb') as file:
    pickle.dump(xgbClf, file)